# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Pull Request Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Install NWA
        run: go install github.com/B1NARY-GR0UP/nwa@4619d499a477881481dd13c32b6e107d2d2a4ccf

      - name: Run License Header Check
        id: license-check
        run: |
          output=$(nwa check -c "BINARY Members" -l apache ./**/*.go ./*.go)
          echo "$output"
          last_line=$(echo "$output" | tail -n 1)
          echo "RESULT=$last_line" >> $GITHUB_ENV

      - name: Verify Check Output
        run: |
          echo "Checking last line of the output:"
          echo "${{ env.RESULT }}"
          if echo "${{ env.RESULT }}" | grep -q 'mismatched=0'; then
            echo "License Header Check passed."
          else
            echo "License Header Check failed."
            exit 1
          fi
